name: klpipe
channels:
  - conda-forge
dependencies:
  - pytest
  - pytest-xdist
  - jupytext
  - astropy
  - corner
  - emcee
  - fitsio
  - galsim
  - jax
  - ipdb
  - pudb
  - jupyter
  - jupyterlab
  - mpi4py
  - numba
  - numpy==1.26.4
  - openmpi
  - schwimmbad
  - scipy
  - snakeviz
  - zeus-mcmc
  - cython
  - sep
  - reproject
  - black
  - pip
